#!/usr/bin/env python3

import os
import sys
from lib import colors
from lib import status
from scan import folder
from scan import ping
from scan import exister
from scan import nmap
from scan import linker

def banner():
    version = "1.2.0"
    print(status.info() + " Authscan   v%s" % version)

def arguments():
    i = 1
    target  =  None
    proto   =  None
    folder  =  "analysis"
    path    =  "custom/basics"
    out     =  "index.html"
    len_arg =  len(sys.argv)

    if len_arg >= 3:
        while i < len_arg:
            if target == None:
                target = sys.argv[i]
            elif proto == None:
                proto = sys.argv[i]
            elif path == "custom/basics" and i == 3:
                if os.path.exists(sys.argv[i]):
                    path = sys.argv[i]
                else:
                    print(status.ko(), "File: '%s' not found" % sys.argv[i])
                    exit(84)
            elif folder == "analysis":
                folder = sys.argv[i]
            i += 1
        resume(target, proto, path, folder)
        choice = input(status.iu() + " Do you want to start the scan [Y|n]: ")
        if choice == 'Y':
            scan(target, path, folder, out, proto)
        else:
            print("\nUsage: <target> <protocol> <attack file> <save folder>")
            print("       Save folder and attack file are optional")
            exit(0)

def source(target, folder, out):
    print(status.st(), "Downloading sources")
    download = folder + "/" + out
    os.system("wget -O " + download + " -q " + target)
    if os.path.isfile(download):
        print(status.ok(), "Sources successfully downloaded")
    else:
        print(status.ko(), "Something went whrong when trying to download sources")
        menu("exit")

def webpaths(target, path, proto, folder):
    print(status.st(), "Brute-forcing the website's urls")
    exister.exister(target, path, proto, folder)
    print(status.ok(), "All the urls have been brute-forced")

def scan(target, path, folder_path, out, proto):
    folder.folder(folder_path)
    ping.ping(target)
    source(target, folder_path, out)
    nmap.nmap(target)
    webpaths(target, path, proto, folder_path)
    linker.linker(target, path, proto, folder_path, out)

def resume(target, proto, path, folder):
    print(status.io() + " Target      : " + colors.red() + str(target) + colors.reset())
    print(status.io() + " Protocol    : " + colors.red() + str(proto) + colors.reset())
    print(status.io() + " Attack file : " + colors.red() + str(path) + colors.reset())
    print(status.io() + " Save folder : " + colors.red() + str(folder) + colors.reset())

def menu(command):
    i = 0
    list_commands = [   "target: ip adress / url website",
                        "exit: leave Authscan",
                        "protocol: protocol used by the target you want to scan",
                        "save: folder to save the scan results",
                        "attack: the file to brutefore the domain",
                        "resume: display the current config for the scan",
                        "exploit: start the scan",
                        None ]
    target  = None
    proto   = None
    path    = "custom/basics"
    folder  = "analysis"
    out     = "index.html"

    while command != "exit":
        command = input(status.iu() + " Command: ")
        if command == "target":
            target = input(status.iu() + " Target: ")
            if target != None:
                print(status.ok(), "Target successfully added")
                if target[len(target) - 1] == '/':
                    target = target[:-1]
            else:
                print(status.ko(), "Target changement failed")
        elif command == "protocol":
            proto = input(status.iu() + " Protocol: ")
            if proto != None:
                print(status.ok(), "Protocol successfully set")
            else:
                print(status.ko(), "Protocol changement failed")
        elif command == "save":
            folder = input(status.iu() + " Save: ")
            if folder != None:
                print(status.ok(), "Save folder successfully set")
            else:
                print(status.ko(), "Save folder changement failed")
        elif command == "attack":
            path = input(status.iu() + " Attack: ")
            print(status.st(), "Checking file's attack")
            if os.path.isfile(path):
                print(status.ok(), "File found")
            else:
                print(status.ko(), "File not found")
                path = None
        elif command == "resume":
            resume(target, proto, path, folder)
        elif command == "exploit":
            if target == None:
                print(status.ko(), "Enter target to scan: 'target'")
            if proto == None:
                print(status.ko(), "Enter protocole to scan: 'protocol'")
            else:
                if path == None:
                    print(status.io(), "To configure the brute-force file, enter: 'path' on menu")
                if folder == "analysis":
                    print(status.io(), "To custom the analysis output folder, enter: 'folder' on menu")
                if path == None:
                    print(status.io(), "To custom and enable the domain's url bruteforce attack, enter: 'attck' on menu")
                scan(target, path, folder, out, proto)
        elif command == "help":
            while list_commands[i] != None:
                print("       " + list_commands[i])
                i += 1
            i = 0
        elif command == "exit":
            print(status.ok(), "Exit")
            return (0)
        else:
            print(status.ko(), "Command not found")

banner()
arguments()
menu(None)